<?php

/** Generated by Latte 3.1.1 */

use Latte\Runtime as LR;

/** source: C:\laragon\www\moje-admin\app\Presentation/@layout.latte */
final class Template_1f23298519 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		echo '<!DOCTYPE html>
<html lang="cs">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>';
		if ($this->hasBlock('title')) /* pos 6:12 */ {
			$this->renderBlock('title', [], function ($s, $type) {
				$ʟ_fi = new LR\FilterInfo($type);
				return LR\Helpers::convertTo($ʟ_fi, 'html', $this->filters->filterContent('stripHtml', $ʟ_fi, $s));
			}) /* pos 6:25 */;
			echo ' | ';
		}
		echo 'EShop Admin</title>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600&display=swap" rel="stylesheet">
    
    <style>
        :root {
            --purple-main: #523091;
            --purple-dark: #271744;
            --glass-bg: rgba(255, 255, 255, 0.75);
            --glass-border: rgba(255, 255, 255, 0.3);
        }

        body {
            font-family: \'Inter\', sans-serif;
            background: linear-gradient(135deg, #250e3c 0%, #440a7d 100%);
            min-height: 100vh;
            color: #333;
            margin: 0;
        }

        /* UI Components Styling */
        .glass-card {
            background: var(--glass-bg);
            backdrop-filter: blur(10px);
            -webkit-backdrop-filter: blur(10px);
            border: 1px solid var(--glass-border);
            border-radius: 15px;
            box-shadow: 0 8px 32px 0 rgba(31, 38, 135, 0.37);
        }

        .navbar-glass {
            background: var(--glass-border);
            backdrop-filter: blur(5px);
            border-bottom: 1px solid rgba(255, 255, 255, 0.1);
        }

        .btn-purple {
            background-color: var(--purple-main);
            color: white;
            border-radius: 8px;
            transition: all 0.3s;
        }

        .btn-purple:hover {
            background-color: var(--purple-dark);
            color: white;
            transform: translateY(-2px);
        }

        /* Toast Notifications */
        .flash-container {
            position: fixed;
            top: 90px;
            right: 20px;
            z-index: 9999;
            pointer-events: none;
        }

        .flash {
            pointer-events: auto;
            min-width: 280px;
            padding: 12px 25px !important;
            margin-bottom: 10px !important;
            border-radius: 50px !important;
            font-size: 0.9rem;
            font-weight: 500;
            box-shadow: 0 4px 15px rgba(0,0,0,0.2) !important;
            border: 1px solid rgba(255,255,255,0.2) !important;
            backdrop-filter: blur(10px);
            display: flex;
            align-items: center;
            animation: slideIn 0.3s ease-out;
        }

        @keyframes slideIn {
            from { transform: translateX(100%); opacity: 0; }
            to { transform: translateX(0); opacity: 1; }
        }

        .form-control { border-radius: 10px; padding: 0.6rem 1rem; }
        .table { background: transparent !important; }
        .table thead th {
            background: rgba(82, 48, 145, 0.1);
            color: var(--purple-dark);
            border-bottom: 2px solid var(--purple-main);
        }
        .text-purple { color: var(--purple-main); }
    </style>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark navbar-glass sticky-top mb-4">
        <div class="container">
            <a href="';
		echo LR\HtmlHelpers::escapeAttr($this->global->uiControl->link('Home:default')) /* pos 100:45 */;
		echo '" class="navbar-brand fw-bold">EShop</a>
            
            <div class="d-flex align-items-center">
';
		if ($user->isLoggedIn()) /* pos 103:23 */ {
			echo '                <span class="text-white me-3 d-none d-md-inline">
                    <small>Uživatel:</small> <strong>';
			echo LR\HtmlHelpers::escapeText($user->getIdentity()->email) /* pos 104:55 */;
			echo '</strong>
                </span>
';
		}
		if ($user->isLoggedIn()) /* pos 106:20 */ {
			echo '                <a href="';
			echo LR\HtmlHelpers::escapeAttr($this->global->uiControl->link('Sign:out')) /* pos 106:47 */;
			echo '" class="btn btn-sm btn-outline-light">Odhlásit se</a>
';
		}
		echo '            </div>
        </div>
    </nav>

    <div class="flash-container">
';
		foreach ($flashes as $flash) /* pos 112:14 */ {
			echo '        <div 
             class="flash glass-card border-0 alert alert-';
			echo LR\HtmlHelpers::escapeAttr($flash->type === 'error' ? 'danger' : 'success') /* pos 113:59 */;
			echo ' shadow">
             <span class="me-2">';
			if ($flash->type === 'error') /* pos 114:33 */ {
			}
			echo '</span>
             ';
			echo LR\HtmlHelpers::escapeText($flash->message) /* pos 115:14 */;
			echo '
        </div>
';

		}

		echo '    </div>

    <div class="container pb-5">
        <main class="glass-card p-4 p-md-5">
';
		$this->renderBlock('content', [], 'html') /* pos 121:13 */;
		echo '        </main>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    
    <script>
        // Auto-dismiss flash messages after 4 seconds
        setTimeout(function() {
            let flashes = document.querySelectorAll(\'.flash\');
            flashes.forEach(el => {
                el.style.transition = "opacity 0.6s ease, transform 0.6s ease";
                el.style.opacity = "0";
                el.style.transform = "translateX(20px)";
                setTimeout(() => el.remove(), 600);
            });
        }, 4000);
    </script>
</body>
</html>';
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['flash' => '112'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		return get_defined_vars();
	}
}
