<?php

/** Generated by Latte 3.1.1 */

use Latte\Runtime as LR;

/** source: C:\laragon\www\moje-admin\app\Presentation\Home/edit.latte */
final class Template_f813fca1b3 extends Latte\Runtime\Template
{
	public const Blocks = [
		['content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		$this->renderBlock('content', get_defined_vars()) /* pos 1:1 */;
	}


	/** {block content} on line 1 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<h1>';
		if (isset($product)) /* pos 2:5 */ {
			echo 'Editace';
		} else /* pos 2:32 */ {
			echo 'Produkt';
		}
		echo '</h1>
';
		$ʟ_tmp = $this->global->uiControl->getComponent('productForm');
		if ($ʟ_tmp instanceof Nette\Application\UI\Renderable) $ʟ_tmp->redrawControl(null, false);
		$ʟ_tmp->render() /* pos 3:1 */;

		echo '<p><a href="';
		echo LR\HtmlHelpers::escapeAttr($this->global->uiControl->link('default')) /* pos 4:7 */;
		echo '">Zpět na seznam</a></p>
';
	}
}
