<?php

/** Generated by Latte 3.1.1 */

use Latte\Runtime as LR;

/** source: C:\laragon\www\moje-admin\app\Presentation\Home/default.latte */
final class Template_0d624f8f44 extends Latte\Runtime\Template
{
	public const Blocks = [
		['content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		$this->renderBlock('content', get_defined_vars()) /* pos 1:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['product' => '64'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		return get_defined_vars();
	}


	/** {block content} on line 1 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '
<div class="d-flex justify-content-between align-items-center mb-5">
    <div>
        <h1 class="fw-bold text-dark m-0" style="letter-spacing: -1px;">Správa produktů</h1>
        <p class="text-muted m-0">Přehled a správa vašeho katalogu</p>
    </div>
    
    <a href="';
		echo LR\HtmlHelpers::escapeAttr($this->global->uiControl->link('edit')) /* pos 9:8 */;
		echo '" class="btn btn-purple px-4 py-2 fw-semibold border-0">
        + Přidat nový produkt
    </a>
</div>

<div class="row mb-5">
    <div class="col-lg-7">
        <div class="p-4 rounded-4" style="background: rgba(255,255,255,0.4); border: 1px solid rgba(255,255,255,0.5);">
            <h5 class="mb-3 fw-bold">Hromadný import (CSV)</h5>
            
            ';
		$form = $this->global->formsStack[] = $this->global->uiControl['importForm'] /* pos 19:13 */;
		Nette\Bridges\FormsLatte\Runtime::initializeForm($form);
		echo Nette\Bridges\FormsLatte\Runtime::renderFormBegin($form, ['class' => 'row g-3']) /* pos 19:13 */;
		echo '
                <div class="col-sm-8">
                    ';
		echo Nette\Bridges\FormsLatte\Runtime::item('csvFile', $this->global)->getControl()->addAttributes(['class' => 'form-control border-0']) /* pos 21:21 */;
		echo '
                </div>
                <div class="col-sm-4">
                    ';
		echo Nette\Bridges\FormsLatte\Runtime::item('send', $this->global)->getControl()->addAttributes(['class' => 'btn btn-dark w-100 fw-bold border-0']) /* pos 24:21 */;
		echo '
                </div>
            ';
		echo Nette\Bridges\FormsLatte\Runtime::renderFormEnd(array_pop($this->global->formsStack)) /* pos 26:13 */;

		echo '
        </div>
    </div>
</div>

<div class="row mb-4">
    <div class="col-md-6 col-lg-4">
        <form action="';
		echo LR\HtmlHelpers::escapeAttr($this->global->uiControl->link('default')) /* pos 33:23 */;
		echo '" method="get" class="d-flex gap-2">
            <div class="input-group input-group-sm">
                <input type="text" name="search"';
		echo LR\HtmlHelpers::formatAttribute(' value', $search) /* pos 35:58 */;
		echo ' 
                       class="form-control border-0 shadow-sm" 
                       placeholder="Hledat podle názvu nebo kódu...">
                <button type="submit" class="btn btn-dark shadow-sm fw-bold">
                    Filtrovat
                </button>
            </div>
';
		if ($search) /* pos 42:79 */ {
			echo '            <a href="';
			echo LR\HtmlHelpers::escapeAttr($this->global->uiControl->link('default')) /* pos 42:16 */;
			echo '" class="btn btn-sm btn-light border shadow-sm">
                Zrušit
            </a>
';
		}
		echo '        </form>
    </div>
</div>

<div class="table-responsive">
    <table class="table table-hover align-middle">
        <thead>
            <tr>
                <th class="ps-3">Stav</th>
                <th>Kód</th>
                <th>Název produktu</th>
                <th>Popis</th>
                <th>Cena</th>
                <th>Skladem</th>
                <th>Historie</th> 
                <th class="text-end pe-3">Akce</th>
            </tr>
        </thead>
        <tbody>
';
		foreach ($products as $product) /* pos 64:17 */ {
			echo '            <tr>
                <td class="ps-3">
                    <span';
			echo ($ʟ_tmp = array_filter(['badge', 'rounded-pill', $product->active ? 'bg-success' : 'bg-secondary'])) ? ' class="' . LR\HtmlHelpers::escapeAttr(implode(" ", array_unique($ʟ_tmp))) . '"' : "" /* pos 66:27 */;
			echo '>
                        ';
			echo LR\HtmlHelpers::escapeText($product->active ? 'Aktivní' : 'Neaktivní') /* pos 67:25 */;
			echo '
                    </span>
                </td>
                <td class="text-dark fw-bold">';
			echo LR\HtmlHelpers::escapeText($product->code) /* pos 70:47 */;
			echo '</td>
                <td class="text-dark">';
			echo LR\HtmlHelpers::escapeText($product->name) /* pos 71:39 */;
			echo '</td>
                
               <td class="text-muted small" style="max-width: 200px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;"';
			echo LR\HtmlHelpers::formatAttribute(' title', $product->description) /* pos 73:143 */;
			echo '>
                    ';
			echo LR\HtmlHelpers::escapeText($product->description) /* pos 74:21 */;
			echo '
                </td>

                <td class="text-purple fw-bold">';
			echo LR\HtmlHelpers::escapeText(($this->filters->number)($product->price, 2, ',', ' ')) /* pos 77:49 */;
			echo ' Kč</td>
                <td>
                    <span';
			echo ($ʟ_tmp = array_filter(['fw-semibold', $product->stock > 0 ? 'text-success' : 'text-danger'])) ? ' class="' . LR\HtmlHelpers::escapeAttr(implode(" ", array_unique($ʟ_tmp))) . '"' : "" /* pos 79:27 */;
			echo '>
                        ';
			echo LR\HtmlHelpers::escapeText($product->stock) /* pos 80:25 */;
			echo ' ks
                    </span>
                </td>
                
                <td class="small">
                    <div class="text-muted" title="Vytvořeno">
                        <span class="opacity-75">Vyt:</span> ';
			echo LR\HtmlHelpers::escapeText(($this->filters->date)($product->created_at, 'd.m.Y H:i')) /* pos 86:62 */;
			echo '
                    </div>
                    <div class="text-dark" title="Upraveno">
                        <span class="opacity-75">Upr:</span> ';
			echo LR\HtmlHelpers::escapeText(($this->filters->date)($product->updated_at, 'd.m.Y H:i')) /* pos 89:62 */;
			echo '
                    </div>
                </td>

                <td class="text-end pe-3">
                    <div class="btn-group btn-group-sm">
                        <a href="';
			echo LR\HtmlHelpers::escapeAttr($this->global->uiControl->link('edit', [$product->id])) /* pos 95:28 */;
			echo '" class="btn btn-light border fw-semibold">
                            Upravit
                        </a>

                        <a href="';
			echo LR\HtmlHelpers::escapeAttr($this->global->uiControl->link('delete!', [$product->id])) /* pos 99:28 */;
			echo '" 
                           onclick="return confirm(\'Opravdu chcete smazat produkt ';
			echo LR\HtmlHelpers::escapeAttr(LR\Helpers::escapeJs($product->name)) /* pos 100:83 */;
			echo '?\')" 
                           class="btn btn-outline-danger border fw-semibold">
                             Smazat
                        </a>
                    </div>
                </td>
            </tr>
';

		}

		echo "\n";
		if (count($products) === 0) /* pos 108:17 */ {
			echo '            <tr>
                <td colspan="8" class="text-center py-5 text-muted"> 
';
			if ($search) /* pos 110:21 */ {
				echo '                        Pro výraz "<strong>';
				echo LR\HtmlHelpers::escapeText($search) /* pos 111:45 */;
				echo '</strong>" nebyly nalezeny žádné produkty.
';
			} else /* pos 112:21 */ {
				echo '                        V databázi zatím nejsou žádné produkty.
';
			}
			echo '                </td>
            </tr>
';
		}
		echo '        </tbody>
    </table>
</div>

';
	}
}
